### ISSUE TITLE
'Failed to parse source map' warning from source-map-loader plugin of Webpack5

### ISSUE THREAD

**Issue by Pavek** [Chris-Baker/pretty-print-object#14]
## Expected Behavior
No Webpack warning

## Current Behavior
Webpack5 (from CRA5 + react-cosmos) warns:

```
WARNING in ./node_modules/@base2/pretty-print-object/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '[...]\node_modules\@base2\pretty-print-object\src\index.ts' file: Error: ENOENT: no such file or directory, open '[...]\node_modules\@base2\pretty-print-object\src\index.ts'
```

## Possible Solution

I guess this is a result of this line from `\node_modules\@base2\pretty-print-object\dist\index.js.map`:
```
// src/index.js:
...
//# sourceMappingURL=index.js.map

// src/index.js.map:                                       vvvvvv
{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings

```

It mentions `../src/index.ts` but the file is missing in npm package. Correct seems to me:
```
"sources":["./index.ts"]
```

## Steps to Reproduce
How do we reproduce this bug? Include code to reproduce, if relevant
1. Setup a project with CRA5 + react-cosmos
2. Run `npm run cosmos`
3. See the warning in console

**Comment by Chris-Baker** [comment]
Thanks @Pavek I've fixed and release version 1.0.2
