### ISSUE TITLE
Make the displayed values take on colour

### ISSUE THREAD

**Issue by lijialiang** [Chris-Baker/pretty-print-object#18]
The native `console.log` prints out the value of the object with a colour so that the comparison container can be distinguished from the `key value`. Just like this:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/12247242/187849872-c21cea18-a422-4fe2-8bca-24d5ac4f97ec.png">

**Comment by Chris-Baker** [comment]
Thanks for the suggestion @lijialiang it's a good one. I am not going to get around to this though but PRs are welcome. Closing this for now. Thanks.
